// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations run as the tables' owner. When the API connects as its own
  // non-owner role (prisma/sql/create-app-role.sql), MIGRATION_DATABASE_URL
  // is the owner's connection; otherwise both are DATABASE_URL.
  datasource: {
    url: process.env["MIGRATION_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
