// Country names for display. Customer.country is free text: the forms store
// an ISO 3166-1 alpha-2 code ("DE"), while the CSV import keeps whatever was
// written ("German", "Germany", "deutsch"). countryName shows all of them as
// the country's English name, and anything it does not recognise as written.

// ISO 3166-1 alpha-2 codes (plus Kosovo's XK) and their English names.
export const COUNTRY_NAMES: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua & Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia & Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "St. Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia & South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard & McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "St. Kitts & Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "St. Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "St. Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "St. Pierre & Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestinian Territories",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "St. Helena",
  SI: "Slovenia",
  SJ: "Svalbard & Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé & Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks & Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad & Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "U.S. Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "St. Vincent & Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis & Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe"
};

// Other ways people write a country: nationalities, local names, short
// forms. Keys are lower case without accents (see key()).
const ALIASES: Record<string, string> = {
  "emirati": "AE",
  "uae": "AE",
  "albanian": "AL",
  "argentine": "AR",
  "argentinian": "AR",
  "argentino": "AR",
  "argentina": "AR",
  "austrian": "AT",
  "osterreich": "AT",
  "oesterreich": "AT",
  "australian": "AU",
  "aussie": "AU",
  "bosnian": "BA",
  "belgian": "BE",
  "belge": "BE",
  "belgie": "BE",
  "belgique": "BE",
  "bulgarian": "BG",
  "brazilian": "BR",
  "brasil": "BR",
  "brasileiro": "BR",
  "brasileira": "BR",
  "belarusian": "BY",
  "canadian": "CA",
  "swiss": "CH",
  "schweiz": "CH",
  "suisse": "CH",
  "svizzera": "CH",
  "suiza": "CH",
  "suizo": "CH",
  "chilean": "CL",
  "chinese": "CN",
  "colombian": "CO",
  "cuban": "CU",
  "cypriot": "CY",
  "czech": "CZ",
  "czech republic": "CZ",
  "czechia": "CZ",
  "cesko": "CZ",
  "german": "DE",
  "deutsch": "DE",
  "deutsche": "DE",
  "deutscher": "DE",
  "deutschland": "DE",
  "alemania": "DE",
  "aleman": "DE",
  "alemana": "DE",
  "danish": "DK",
  "dane": "DK",
  "danmark": "DK",
  "danes": "DK",
  "danesa": "DK",
  "algerian": "DZ",
  "estonian": "EE",
  "egyptian": "EG",
  "spanish": "ES",
  "espanol": "ES",
  "espanola": "ES",
  "espana": "ES",
  "canarian": "ES",
  "canario": "ES",
  "canaria": "ES",
  "finnish": "FI",
  "finn": "FI",
  "suomi": "FI",
  "french": "FR",
  "francais": "FR",
  "francaise": "FR",
  "francia": "FR",
  "frances": "FR",
  "francesa": "FR",
  "british": "GB",
  "uk": "GB",
  "united kingdom": "GB",
  "great britain": "GB",
  "britain": "GB",
  "england": "GB",
  "english": "GB",
  "scotland": "GB",
  "scottish": "GB",
  "wales": "GB",
  "welsh": "GB",
  "northern ireland": "GB",
  "northern irish": "GB",
  "reino unido": "GB",
  "ingles": "GB",
  "inglesa": "GB",
  "greek": "GR",
  "hellenic": "GR",
  "griego": "GR",
  "griega": "GR",
  "croatian": "HR",
  "croat": "HR",
  "hrvatska": "HR",
  "hungarian": "HU",
  "magyar": "HU",
  "indonesian": "ID",
  "irish": "IE",
  "eire": "IE",
  "israeli": "IL",
  "indian": "IN",
  "iranian": "IR",
  "persian": "IR",
  "icelandic": "IS",
  "icelander": "IS",
  "italian": "IT",
  "italiano": "IT",
  "italiana": "IT",
  "italia": "IT",
  "japanese": "JP",
  "kenyan": "KE",
  "korean": "KR",
  "south korean": "KR",
  "lithuanian": "LT",
  "luxembourgish": "LU",
  "luxembourger": "LU",
  "latvian": "LV",
  "moroccan": "MA",
  "marroqui": "MA",
  "marruecos": "MA",
  "montenegrin": "ME",
  "macedonian": "MK",
  "north macedonian": "MK",
  "maltese": "MT",
  "mexican": "MX",
  "mexicano": "MX",
  "mexicana": "MX",
  "malaysian": "MY",
  "nigerian": "NG",
  "dutch": "NL",
  "holland": "NL",
  "netherlands": "NL",
  "the netherlands": "NL",
  "nederland": "NL",
  "nederlands": "NL",
  "holandes": "NL",
  "holandesa": "NL",
  "norwegian": "NO",
  "norge": "NO",
  "noruego": "NO",
  "noruega": "NO",
  "new zealander": "NZ",
  "kiwi": "NZ",
  "peruvian": "PE",
  "filipino": "PH",
  "filipina": "PH",
  "philippine": "PH",
  "pakistani": "PK",
  "polish": "PL",
  "pole": "PL",
  "polska": "PL",
  "polaco": "PL",
  "polaca": "PL",
  "portuguese": "PT",
  "portugues": "PT",
  "portuguesa": "PT",
  "romanian": "RO",
  "rumano": "RO",
  "rumana": "RO",
  "serbian": "RS",
  "serb": "RS",
  "russian": "RU",
  "russia": "RU",
  "ruso": "RU",
  "rusa": "RU",
  "saudi": "SA",
  "saudi arabian": "SA",
  "swedish": "SE",
  "swede": "SE",
  "sverige": "SE",
  "sueco": "SE",
  "sueca": "SE",
  "singaporean": "SG",
  "slovenian": "SI",
  "slovene": "SI",
  "slovak": "SK",
  "slovakian": "SK",
  "senegalese": "SN",
  "thai": "TH",
  "tunisian": "TN",
  "turkish": "TR",
  "turk": "TR",
  "turkey": "TR",
  "turquia": "TR",
  "turco": "TR",
  "turca": "TR",
  "ukrainian": "UA",
  "ucraniano": "UA",
  "ucraniana": "UA",
  "american": "US",
  "usa": "US",
  "u.s.": "US",
  "u.s.a.": "US",
  "united states of america": "US",
  "america": "US",
  "estadounidense": "US",
  "uruguayan": "UY",
  "venezuelan": "VE",
  "vietnamese": "VN",
  "south african": "ZA"
};

function key(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

// The English names themselves, matched the same way ("germany", "ESPAÑA"…).
const BY_NAME: Record<string, string> = Object.fromEntries(Object.entries(COUNTRY_NAMES).map(([code, name]) => [key(name), code]));

// The ISO code a stored country stands for, or null when it is not recognised.
export function countryCode(value: string | null | undefined): string | null {
  if (!value) return null;
  const text = value.trim();
  if (/^[A-Za-z]{2}$/.test(text)) {
    const code = text.toUpperCase() === "UK" ? "GB" : text.toUpperCase();
    if (COUNTRY_NAMES[code]) return code;
  }
  const k = key(text);
  return BY_NAME[k] ?? ALIASES[k] ?? null;
}

// "DE", "German" and "germany" → "Germany"; anything unrecognised as written.
export function countryName(value: string | null | undefined): string {
  if (!value) return "";
  const code = countryCode(value);
  return code ? COUNTRY_NAMES[code] : value.trim();
}
