-- CreateTable
CREATE TABLE "DiveSite" (
    "id" TEXT NOT NULL,
    "nameEs" TEXT NOT NULL,
    "nameEn" TEXT NOT NULL,
    "nameDe" TEXT NOT NULL,
    "nameFr" TEXT NOT NULL,
    "descriptionEs" TEXT NOT NULL,
    "descriptionEn" TEXT NOT NULL,
    "descriptionDe" TEXT NOT NULL,
    "descriptionFr" TEXT NOT NULL,
    "latitude" DECIMAL(10,7) NOT NULL,
    "longitude" DECIMAL(10,7) NOT NULL,
    "depthMin" INTEGER NOT NULL,
    "depthMax" INTEGER NOT NULL,
    "requiredCertLevel" INTEGER NOT NULL,
    "difficultyLevel" INTEGER NOT NULL,
    "typicalVisibility" INTEGER,
    "typicalCurrent" TEXT NOT NULL DEFAULT 'none',
    "waterTempRange" JSONB NOT NULL,
    "marineLife" JSONB NOT NULL,
    "pointsOfInterest" JSONB NOT NULL,
    "bestSeason" JSONB NOT NULL,
    "travelTimeMinutes" INTEGER NOT NULL,
    "maxDiversPerTrip" INTEGER NOT NULL,
    "accessibility" TEXT NOT NULL DEFAULT 'boat_only',
    "facilities" JSONB NOT NULL,
    "restrictions" JSONB,
    "photos" JSONB NOT NULL DEFAULT '[]',
    "totalDives" INTEGER NOT NULL DEFAULT 0,
    "averageRating" DECIMAL(3,2),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DiveSite_pkey" PRIMARY KEY ("id")
);
